name       : python-pytest-benchmark
version    : 3.4.1
release    : 3
source     :
    - https://github.com/ionelmc/pytest-benchmark/archive/refs/tags/v3.4.1.tar.gz : d085da6cd20644f83d88cd6d1a0f084712e49c31f742200a405ddf252b6065e8
homepage   : https://github.com/ionelmc/pytest-benchmark
license    : BSD-2-Clause
component  : programming.python
summary    : py.test fixture for benchmarking code
description: |
    A pytest fixture for benchmarking code. It will group the tests into rounds that are calibrated to the chosen timer.
#builddeps  :
#    - python-freezegun # check
#    - python-pytest # check
rundeps    :
    - python-py-cpuinfo
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    needs elasticsearch packaged
#    %python3_test pytest3
