name       : python-pytest-benchmark
version    : 3.2.3
release    : 1
source     :
    - https://github.com/ionelmc/pytest-benchmark/archive/v3.2.3.tar.gz : 672822208aa14365478bf67566074c03e3493f0891cd43b43eed164e2362cbcb
homepage   : https://github.com/ionelmc/pytest-benchmark
license    : BSD-2-Clause
component  : programming.python
summary    : py.test fixture for benchmarking code
description: |
    A pytest fixture for benchmarking code. It will group the tests into rounds that are calibrated to the chosen timer.    
rundeps    :
    - python-py-cpuinfo
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
