name       : python-pytest-benchmark
version    : 4.0.0
release    : 5
source     :
    - https://github.com/ionelmc/pytest-benchmark/archive/refs/tags/v4.0.0.tar.gz : 42ae209b04764022a286524f2ed32deb35432f997430b067105896f8a990c5f1
homepage   : https://github.com/ionelmc/pytest-benchmark
license    : BSD-2-Clause
component  : programming.python
summary    : py.test fixture for benchmarking code
description: |
    A pytest fixture for benchmarking code. It will group the tests into rounds that are calibrated to the chosen timer.
#builddeps  :
#    - python-freezegun # check
#    - python-pytest # check
rundeps    :
    - python-py-cpuinfo
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    needs python-elasticsearch packaged
#    %python3_test pytest3
